# Generated by Django 4.0.4 on 2022-06-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_text', models.CharField(max_length=200)),
                ('warehouse_img', models.FileField(upload_to='media/')),
            ],
        ),
    ]
