# Generated by Django 4.0.4 on 2022-06-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_img',
            field=models.FileField(upload_to=''),
        ),
    ]
